substitutions:
  _REGION: europe-west1
  _REPO: cloud-run-source-deploy
  _IMAGE_PATH: $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/laxmi-chit-fund:$COMMIT_SHA

steps:
  - name: "docker/compose:2.19.1"
    id: "build-tests"
    args: ["-f", "docker-compose-tests.yaml", "up", "-d"]
    dir: "backend"

  - name: "docker/compose:2.19.1"
    id: "run-tests"
    args:
      [
        "-f",
        "docker-compose-tests.yaml",
        "run",
        "-e",
        "PYTEST_ARGS=--maxfail=1 -v",
        "tests",
      ]
    dir: "backend"
    waitFor: ["build-tests"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "$_IMAGE_PATH", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_IMAGE_PATH"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "laxmi-chit-fund"
      - "--image"
      - "$_IMAGE_PATH"
      - "--region"
      - "europe-west1"
    waitFor: ["push-backend"]

images:
  - "$_IMAGE_PATH"
