steps:
  # - name: "docker/compose"
  #   id: "build-tests"
  #   args: ["-f", "docker-compose-tests.yaml", "up", "-d"]
  #   dir: "backend"

  # - name: "docker/compose"
  #   id: "run-tests"
  #   args:
  #     [
  #       "-f",
  #       "docker-compose-tests.yaml",
  #       "run",
  #       "-e",
  #       "PYTEST_ARGS='--maxfail=1 -v'",
  #       "tests",
  #     ]
  #   dir: "backend"
  #   waitFor: ["build-tests"]

  - name: "gcr.io/cloud-builders/docker"
    id: "build-backend"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/laxmi-chit-fund:$COMMIT_SHA", "."]
    dir: "backend"
    # waitFor: ["run-tests"]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-backend"
    args: ["push", "gcr.io/$PROJECT_ID/laxmi-chit-fund:$COMMIT_SHA"]
    waitFor: ["build-backend"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "laxmi-chit-fund"
      - "--image"
      - "gcr.io/$PROJECT_ID/laxmi-chit-fund:$COMMIT_SHA"
      - "--region"
      - "europe-west1"
    waitFor: ["push-backend"]

images:
  - "gcr.io/$PROJECT_ID/laxmi-chit-fund:$COMMIT_SHA"
