version: "3.11"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - firestore-emulator
    container_name: laxmi-chit-fund-api
    working_dir: /app
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      PORT: 2000
      PYTHONDONTWRITEBYTECODE: 1
      GCLOUD_PROJECT: demo-laxmi-chit-fund-letsgetit
    ports:
      - 2000:2000
    command: uvicorn app.main:app --host 0.0.0.0 --port 2000 --reload
    restart: on-failure

  firestore-emulator:
    image: mtlynch/firestore-emulator
    environment:
      PORT: 2021
      FIRESTORE_PROJECT_ID: demo-laxmi-chit-fund-letsgetit
    ports:
      - 2021:2021
