version: "3.8"

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - firestore-emulator
    working_dir: /app
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      GCLOUD_PROJECT: demo-laxmi-chit-fund-letsgetit
    command: sh -c "pytest ${PYTEST_ARGS}"

  firestore-emulator:
    image: spine3/firebase-emulator
    environment:
      PORT: 2021
      UI_ENABLED: True
      UI_EMULATOR_PORT: 2020
      FIRESTORE_EMULATOR_PORT: 2021
      GCP_PROJECT: demo-laxmi-chit-fund-letsgetit
    ports:
      - 2020:2020
      - 2021:2021
