version: "3.11"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - firebase-emulator
    container_name: laxmi-chit-fund-api
    working_dir: /app
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      PORT: 2000
      PYTHONDONTWRITEBYTECODE: 1
      GCLOUD_PROJECT: demo-laxmi-chit-fund-letsgetit
    ports:
      - 2000:2000
    command: uvicorn app.main:app --host 0.0.0.0 --port 2000 --reload
    restart: on-failure

  firebase-emulator:
    image: spine3/firebase-emulator
    environment:
      PORT: 2021
      UI_ENABLED: "true"
      UI_EMULATOR_PORT: 2020
      FIRESTORE_EMULATOR_PORT: 2021
      GCP_PROJECT: demo-laxmi-chit-fund-letsgetit
    ports:
      - 2020:2020
      - 2021:2021
