steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - cf-scrape-candlesticks
      - --region=europe-west1
      - --source=.
      - --trigger-http
      - --runtime=python39
      - --entry-point=main
      - --memory=128M
      - --max-instances=1
      - --set-env-vars=PROJECT_ID=${PROJECT_ID}
      - --set-env-vars=UPSTOX_API_URL=${_UPSTOX_API_URL}
      - --set-env-vars=LAXMI_API_URL=${_LAXMI_API_URL}
    dir: "cloud-functions/scrape-candlesticks"
    secretEnv: ["LAXMI_CUD_API_KEY"]

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/CUD_API_KEY/versions/latest
      env: "LAXMI_CUD_API_KEY"
