steps:
  - name: "python:3.9"
    id: "install-dependencies"
    dir: "cloud-functions/scrape-candlesticks"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

  - name: "python:3.9"
    id: "tests"
    dir: "cloud-functions/scrape-candlesticks"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        source venv/bin/activate
        python -m unittest

  - name: "python:3.9"
    id: "remove-venv"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        rm -rf venv

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - cf-scrape-candlesticks
      - --region=europe-west1
      - --source=.
      - --trigger-http
      - --timeout=300s
      - --runtime=python39
      - --entry-point=main
      - --memory=128M
      - --max-instances=1
      - --set-env-vars=PROJECT_ID=${PROJECT_ID}
      - --set-env-vars=UPSTOX_API_URL=${_UPSTOX_API_URL}
      - --set-env-vars=LAXMI_API_URL=${_LAXMI_API_URL}
      - --set-secrets=LAXMI_CUD_API_KEY=projects/${PROJECT_ID}/secrets/CUD_API_KEY/versions/latest
    dir: "cloud-functions/scrape-candlesticks"
    waitFor: ["tests"]
